	<div class="conteudo-admin">
	<h2>Gerenciar Combos</h2>
	<div class="forms-admin">
		<div class="link-text">
		<a href="<?PHP echo $this->url(array('action' => 'adicionar')); ?>">ADICIONAR NOVO COMBO <img alt="" src="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/img/new.png' ?>"></a> 
		</div>
		<table border="1" width="98%">
			<tr class="linha3">
				<th>Imagem</th>
				<th>Nome</th>
				<th>Produto 1</th>
				<th>Produto 2</th>
				<th>Produto 3</th>
				<th>Produto 4</th>
				<th>Produto 5</th>
				<th>Preço</th>
				<th align="center">Editar</th>
				<th align="center">Remover</th>
			</tr>
		<?php $linha = 0;?>
		<?PHP foreach ($this->combo as $combo): ?>
			<?php 
			$id = array($combo['id_produto1'],$combo['id_produto2'],$combo['id_produto3'],$combo['id_produto4'],$combo['id_produto5']);
			
			$produtoModel = new Application_Model_Produto();

			for($i = 0;$i < 5;$i++){
				if($id[$i] != null){
					$idx = $id[$i];
					$produto[$i] = $produtoModel->fetchAll(
											$produtoModel->select()
											->from($produtoModel->info(Zend_Db_Table_Abstract::NAME))
											->columns(array('nome'))
											->where('id_produto LIKE :idx')
												->bind(array(
													'idx' => '%' . $idx . '%'
												))

					);
				}else{ $produto[$i][0]['nome'] = 'nenhum';}
			}
			?>
			<?php 
			if($linha == 0){
				echo '<tr class="linha1">';
				$linha = 1;
			}else{
				echo '<tr class="linha2">';
				$linha = 0;
			}
			?>
				<?php $imagem = 'img/produtos/'. $combo['id_produto_combo'] . '.jpg';?>
				<?php if(file_exists($imagem)):?>
					<td align="center"><img width="100" height="100" src=<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/img/produtos/'. $combo['id_produto_combo'] . '.jpg'; ?> alt="<?PHP echo $combo['nome']; ?>" title="<?PHP echo $combo['nome']; ?>" /></td>
				<?php else:?>
					<td align="center"><img width="100" height="100" src=<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/img/produtos/sem-foto.gif'; ?> alt="<?PHP echo $combo['nome']; ?>" title="<?PHP echo $combo['nome']; ?>" /></td>				
				<?php endif;?>
				<td><?PHP echo $combo['nome']; ?></td>
				<td><?PHP echo $produto[0][0]['nome']; ?></td>
				<td><?PHP echo $produto[1][0]['nome']; ?></td>
				<td><?PHP echo $produto[2][0]['nome']; ?></td>
				<td><?PHP echo $produto[3][0]['nome']; ?></td>
				<td><?PHP echo $produto[4][0]['nome']; ?></td>
				<td><?PHP echo 'R$ ' . number_format($combo['preco'] / 100, 2, ',', '.'); ?></td>
				<td align="center"><a href="<?PHP echo $this->url(array('action' => 'editar', 'id' => $combo['id_combo'])); ?>"><img alt="editar" src="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/img/edit.png' ?>"></a></td>
				<td align="center"><a href="<?PHP echo $this->url(array('action' => 'remover', 'id' => $combo['id_combo'])); ?>"><img alt="excluir" src="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/img/delete.png' ?>"></a></td>
			</tr>
		<?PHP endforeach; ?>
		</table>
		<br />
			<input type="button" value=" Voltar " onclick="window.location='<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/admin' ?>'">	
		</div>
	
	</div>

