
	<div class="conteudo-admin">
		<h2>Novidades</h2>
		<div class="forms-admin">

		<div class="link-text">
		<a href="<?PHP echo $this->url(array('action' => 'adicionar')); ?>">Adicionar Novidade <img alt="editar" src="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/img/new.png' ?>"></a>
		</div>
    <table border="1" width="98%">
        <tr class="linha3">
            <th>Id</th>
            <th>Título</th>
            <th>Texto</th>
            <th align="center">Editar</th>
            <th align="center">Remover</th>
        </tr>
		<?php $linha = 0;?>
    <?PHP foreach ($this->novidades as $novidade): ?>
        <?php 
			if($linha == 0){
				echo '<tr class="linha1">';
				$linha = 1;
			}else{
				echo '<tr class="linha2">';
				$linha = 0;
			}
			?>
            <td><?PHP echo $novidade['id_noticia']; ?></td>
            <td><?PHP echo $novidade['titulo']; ?></td>
            <td><?PHP echo $novidade['texto']; ?></td>
            <td align="center"><a href="<?PHP echo $this->url(array('action' => 'editar', 'id' => $novidade['id_noticia'])); ?>"><img alt="editar" src="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/img/edit.png' ?>"></a></td>
            <td align="center"><a href="<?PHP echo $this->url(array('action' => 'remover', 'id' => $novidade['id_noticia'])); ?>"><img alt="excluir" src="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/img/delete.png' ?>"></a></td>
        </tr>
    <?PHP endforeach; ?>
    </table>
	<br />
	<input type="button" value=" Voltar " onclick="window.location='<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/admin' ?>'">	
		</div>
	</div>	
