	<div class="conteudo-admin">
	<h2>Gerenciar Relacionamentos - <?php print_r($this->nome_ingrediente);?></h2>
	<div class="forms-admin">
		
		<p><a href="<?PHP echo $this->url(array('action' => 'adicionar')); ?>">NOVO RELACIONAMENTO</a> 
		<table border="1" width="98%">
			<tr class="linha3">
				<th>Produto</th>
				<th>Opcional</th>
				<th>Adicional</th>
				<th>Quantidade Padrão</th>
				<th>Quantidade Máxima</th>
				<th>Quantidade Mínima</th>
				<th align="center">Editar</th>
				<th align="center">Remover</th>
			</tr>
			<?php $linha = 0;?>
		<?PHP foreach ($this->relacionamento as $relacionamento): ?>
			<?php 
			if($linha == 0){
				echo '<tr class="linha1">';
				$linha = 1;
			}else{
				echo '<tr class="linha2">';
				$linha = 0;
			}
			?>
				<?php 
					$busca = $relacionamento['id_produto'];

					$produtoModel = new Application_Model_Produto();
						$nome_produto = $produtoModel->fetchAll(
											$produtoModel->select()
												->from($produtoModel->info(Zend_Db_Table_Abstract::NAME))
												->columns(array('nome'))
												->where('id_produto like :busca')
												->bind(array(
												'busca' => '%' . $busca . '%'
												))
											);
				?>
				<td><?PHP echo $nome_produto[0]['nome']; ?></td>
				<td><?PHP if($relacionamento['opcional'] == 1){echo 'Sim';}else{echo 'Não';}?></td>
				<td><?PHP if($relacionamento['adicional'] == 1){echo 'Sim';}else{echo 'Não';}?></td>
				<td><?PHP echo $relacionamento['qtd_padrao']; ?></td>
				<td><?PHP echo $relacionamento['qtd_max']; ?></td>
				<td><?PHP echo $relacionamento['qtd_min']; ?></td>
				<td align="center"><a href="<?PHP echo $this->url(array('action' => 'editar', 'id' => $relacionamento['id_ingrediente_idx'])); ?>">Editar</a></td>
				<td align="center"><a href="<?PHP echo $this->url(array('action' => 'remover', 'id' => $relacionamento['id_ingrediente_idx'])); ?>">Excluir</a></td>
			</tr>
		<?PHP endforeach; ?>
		</table>
			<input type="button" value=" Voltar " onclick="history.go(-1)">	
		</div>
	
	</div>

