	<div class="conteudo-admin">
	<h2>Administrador</h2>
	<div>
	<ul class="menus-admin">

    <a href="<?PHP echo $this->url(array('controller' => 'pedido')); ?>"><li class="button-admin">Pedidos</li></a>
    <a href="<?PHP echo $this->url(array('controller' => 'ingrediente')); ?>"><li class="button-admin">Cadastrar ingrediente</li></a>
    <a href="<?PHP echo $this->url(array('controller' => 'produto')); ?>"><li class="button-admin">Cadastrar produto</li></a>
	<a onclick="window.open('http://news.mundoorange.com.br', 'Pagina', 'STATUS=NO, TOOLBAR=NO, LOCATION=NO, DIRECTORIES=NO, RESISABLE=NO, SCROLLBARS=NO, TOP=0, LEFT=0, WIDTH=1000, HEIGHT=700');" href="#"><li class="button-admin">Newsletter</li></a>  
	<a href="<?PHP echo $this->url(array('controller' => 'comocomprar')); ?>"><li class="button-admin">Como Comprar</li></a>
    <a href="<?PHP echo $this->url(array('controller' => 'contatos', 'action' => 'index', 'respondida' => 0)); ?>"><li class="button-admin">Contatos</li></a>
    <a href="<?PHP echo $this->url(array('controller' => 'galeria')); ?>"><li class="button-admin">Galeria</li></a>
    <a href="<?PHP echo $this->url(array('controller' => 'novidades')); ?>"><li class="button-admin">Novidades</li></a>
    <a href="<?PHP echo $this->url(array('controller' => 'midias', 'action' => 'index', 'id' => 1)); ?>"><li class="button-admin">Midias</li></a>
    <a href="<?PHP echo $this->url(array('controller' => 'categoria')); ?>"><li class="button-admin">Categorias</li></a>
    <a href="<?PHP echo $this->url(array('controller' => 'menus', 'action' => 'index', 'id' => '1')); ?>"><li class="button-admin">Menu Sobre Nós</li></a>
    <a href="<?PHP echo $this->url(array('controller' => 'combo')); ?>"><li class="button-admin">Combos</li></a>
    <a href="<?PHP echo $this->url(array('module' => '','controller' => 'alterardados')); ?>"><li class="button-admin">Alterar Dados</li></a>
    <a href="http://www.muitomaissite.com.br/rodrigo/maps/"><li class="button-admin">Mapa de Entrega</li></a>

	</ul>
	</div>	
	</div>
		

