
	<div class="menu-left">
			<h2>Categorias</h2>
				<ul>
					<li>Categoria 1</li>
					<li>Categoria 2</li>
					<li>Categoria 3</li>
					<li>Categoria 4</li>
					<li>Categoria 5</li>
					<li>Categoria 6</li>
					<li>Categoria 7</li>
					<li>Categoria 8</li>
				</ul>
		</div>
	<div class="conteudo">
		<div class="telaCadastro2">
	<h2>Mudar Senha</h2>
	<?PHP echo $this->form; ?>
	* Indica campo obrigatório
	<?php if($this->aviso){ echo $this->aviso; } ?>

</div>		
	</div>
